-- MySQL Script generated by MySQL Workbench
-- ven. 05 déc. 2025 14:39:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tournament_wintercup
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tournament_wintercup` ;

-- -----------------------------------------------------
-- Schema tournament_wintercup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tournament_wintercup` DEFAULT CHARACTER SET utf8 ;
USE `tournament_wintercup` ;

-- -----------------------------------------------------
-- Table `tournament_wintercup`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tournament_wintercup`.`teams` ;

CREATE TABLE IF NOT EXISTS `tournament_wintercup`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `creation_date_UNIQUE` (`creation_date` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tournament_wintercup`.`tournament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tournament_wintercup`.`tournament` ;

CREATE TABLE IF NOT EXISTS `tournament_wintercup`.`tournament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(9) NOT NULL,
  `place` INT NOT NULL,
  `ranking` INT NOT NULL,
  `matchs_day` DATE NOT NULL,
  `teams_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ranking_UNIQUE` (`ranking` ASC) VISIBLE,
  UNIQUE INDEX `place_UNIQUE` (`place` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_tournament_teams1_idx` (`teams_id` ASC) VISIBLE,
  CONSTRAINT `fk_tournament_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `tournament_wintercup`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tournament_wintercup`.`coaches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tournament_wintercup`.`coaches` ;

CREATE TABLE IF NOT EXISTS `tournament_wintercup`.`coaches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(30) NOT NULL,
  `type` TINYINT NOT NULL,
  `teams_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coaches_teams1_idx` (`teams_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_coaches` (`lastname` ASC, `firstname` ASC) VISIBLE,
  CONSTRAINT `fk_coaches_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `tournament_wintercup`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tournament_wintercup`.`highschool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tournament_wintercup`.`highschool` ;

CREATE TABLE IF NOT EXISTS `tournament_wintercup`.`highschool` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `adress` VARCHAR(50) NOT NULL,
  `prefecture` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tournament_wintercup`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tournament_wintercup`.`players` ;

CREATE TABLE IF NOT EXISTS `tournament_wintercup`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(30) NOT NULL,
  `age` INT NOT NULL,
  `tall` INT NOT NULL,
  `position` VARCHAR(2) NOT NULL,
  `highschool_id` INT NOT NULL,
  `teams_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lastname_UNIQUE` (`lastname` ASC) VISIBLE,
  UNIQUE INDEX `firstname_UNIQUE` (`firstname` ASC) VISIBLE,
  INDEX `fk_players_highschool_idx` (`highschool_id` ASC) VISIBLE,
  INDEX `fk_players_teams1_idx` (`teams_id` ASC) VISIBLE,
  CONSTRAINT `fk_players_highschool`
    FOREIGN KEY (`highschool_id`)
    REFERENCES `tournament_wintercup`.`highschool` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `tournament_wintercup`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tournament_wintercup`.`statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tournament_wintercup`.`statistics` ;

CREATE TABLE IF NOT EXISTS `tournament_wintercup`.`statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `statistics_points` INT NOT NULL,
  `statistics_assists` INT NOT NULL,
  `statistics_rebounds` INT NOT NULL,
  `statistics_blocks` INT NOT NULL,
  `statistics_steals` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tournament_wintercup`.`players_has_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tournament_wintercup`.`players_has_statistics` ;

CREATE TABLE IF NOT EXISTS `tournament_wintercup`.`players_has_statistics` (
  `players_id` INT NOT NULL,
  `statistics_id` INT NOT NULL,
  INDEX `fk_players_has_statistics_statistics1_idx` (`statistics_id` ASC) VISIBLE,
  INDEX `fk_players_has_statistics_players1_idx` (`players_id` ASC) VISIBLE,
  CONSTRAINT `fk_players_has_statistics_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `tournament_wintercup`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_has_statistics_statistics1`
    FOREIGN KEY (`statistics_id`)
    REFERENCES `tournament_wintercup`.`statistics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
